Repository ziomciopoziomcio/snake_ai, pull requests merged in 2024-08, with the labels that each got.

#4 #1 error fix
  main.py
Labels: Fix

#5 #3 error fix
  components/snake_helper.py
Labels: Fix

#8 #7 improved efficienty
  main.py
Labels: enhancement, improvement

#14 snake being able to hit itself - issue fixed
  .idea/.gitignore
  main.py
Labels: Fix

#15 Added parameters gui
  .idea/misc.xml
  components/parameters.py
  main.py
Labels: enhancement

#17 game does not spawn apples on snake
  .idea/misc.xml
  main.py
Labels: Fix

#18 board malfunction when changing size fixed
  main.py
Labels: Fix

#19 update
  main.py
Labels: update

#20 Showing score during the game
  main.py
Labels: enhancement

#25 Added different types of scoreboard
  .idea/misc.xml
  components/board_helper.py
  components/parameters.py
  main.py
Labels: enhancement

#29 #28 fix
  main.py
Labels: Fix

#30 Custom game modes
  components/parameters.py
  components/snake_helper.py
  main.py
Labels: enhancement
